# Generated by Django 3.2.8 on 2021-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('passw_hash', models.BinaryField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.BinaryField(max_length=64)),
                ('K2', models.BinaryField(max_length=64)),
                ('K3', models.BinaryField(max_length=64)),
            ],
        ),
    ]
