# Generated by Django 3.2.8 on 2021-10-07 16:32

from django.db import migrations, models
from secrets import token_bytes

class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passw_salt',
            field=models.BinaryField(default=token_bytes(24), max_length=24),
            preserve_default=False,
        ),
    ]
